### ISSUE TITLE
Benefits over "ss" command

### ISSUE THREAD

**Issue by WatchDogsDev** [pooladkhay/xdp-ip-counter#4]
Hi, Thanks for your nice work.

What are the benefits of this project compared to "ss" command for example ?

**Comment by pooladkhay** [comment]
ss is a more general-purpose tool. xdp-ip-counter is developed with (almost) a single aim and it operates at a much lower level than ss which leads to performance benefits.
More about XDP: [https://en.wikipedia.org/wiki/Express_Data_Path](https://en.wikipedia.org/wiki/Express_Data_Path)
